### ISSUE TITLE
Authorization token failure for backround.rb

### ISSUE THREAD

**Issue by Nick-Harvey** [SUSE/caasp-services#26]
I opened up https://github.com/SUSE/Portus/issues/1624 under the portus repo, however, I'm beginning to think it's more relevant here. This is the last obstacle to overcome for my application deployment :). Everything else is working perfectly, I just need to get the UI to update with registry events.

**Comment by bonhamjp** [comment]
Hey @Nick-Harvey I haven't tried running `bundle exec rails r bin/background.rb` from the container. On the other Portus chart that I have been collaborating on I ended up adding a second container to the deployment, which runs the background processing. I did this by setting an ENV var `PORTUS_BACKGROUND: true` in the second container.

You can see that deployment here: https://github.com/bonhamjp/charts/blob/feature/portus-default-insecure/stable/portus/templates/portus-deploy.yaml#L143

I haven't seen the token issue come up, but that chart is not using an NGINX reverse proxying.

**Comment by stefsuse** [comment]
Closing this issue as the work for this is being tracked in the other issue and the chart has had many updates since then.
