### ISSUE TITLE
Error: found in requirements.yaml, but missing in charts/ directory: mariadb

### ISSUE THREAD

**Issue by feluxe** [SUSE/caasp-services#27]
Hi there!

If I clone the repo and run:

    helm install --name portus --namespace kube-system contrib/helm-charts/portus

I get the following error:

> Error: found in requirements.yaml, but missing in charts/ directory: mariadb

**Comment by bonhamjp** [comment]
Hello @feluxe have you tried running `helm dependency build contrib/helm-charts/portus`? That should fetch the mariadb chart for you, and place it in the charts directory of the Portus chart.

**Comment by feluxe** [comment]
It works. I wasn't aware this was possible. Thanks for the info! :)
